### ISSUE TITLE
TransactionFailureException: Unable to commit transaction if there are errors in update statement

### ISSUE THREAD

**Issue by agre1981** [fbiville/liquigraph#129] opened 2016-10-03 08:48 UTC
I use liquigraph with embbed DB (neo4j 2.1.7) and have such error.
Use case: 
1/ have any error in query changelog.xml like this:
`<query>DROP CONSTRAINTX ON (cc:Content) ASSERT cc.code IS UNIQUE</query>`
2/ run update with code

```
        Liquigraph liquigraph = new Liquigraph();
        org.liquigraph.core.configuration.Configuration configuration = new ConfigurationBuilder()
                .withMasterChangelogLocation("changelog.xml")
                .withDataSource(new Neo4jDataSource(graphDatabaseService))
                .withRunMode().build();

        liquigraph.runMigrations(configuration);
```

Comments:
1/ during exception we do not rollback transaction. it makes transaction status to Status.STATUS_MARKED_ROLLBACK 
ChangelogGraphWriter

```
    private StatementExecution executeStatement(Changeset changeset) {
        try {
            Precondition precondition = changeset.getPrecondition();
            boolean preconditionResult = executePrecondition(precondition);

            if (!preconditionResult) {
                return handleFailedPrecondition(precondition, changeset);
            }

            boolean postcondition;
            do {
                try (Statement statement = writeConnection.createStatement()) {
                    for (String query : changeset.getQueries()) {
                        statement.execute(query);
                    }
                    writeConnection.commit();
                }

                postcondition = executePostcondition(changeset.getPostcondition());
            } while (postcondition);
        } catch (SQLException e) {
            throw propagate(e);
        }
        return StatementExecution.SUCCESS;
    }
```

2/ During closing connection in MigrationRunner.runMigrations(Configuration configuration) we remove lock in LiquigraphLock.releaseLock(Connection connection). It causes exception because transaction has status Status.STATUS_MARKED_ROLLBACK. 
It lives lock on DB and not allow to update it again without manually removing it from DB.
org.neo4j.graphdb.TransactionFailureException: Unable to commit transaction
javax.transaction.RollbackException: Tx status is: STATUS_MARKED_ROLLBACK

3/ recommendation: Add rollback if exception accured.
ChangelogGraphWriter

```
    private StatementExecution executeStatement(Changeset changeset) {
        try {
                    writeConnection.commit();

        } catch (SQLException e) {
            writeConnection.rollback(); // to add
            throw propagate(e);
        }
```

**Comment by fbiville** [comment] 2016-10-10 14:03
@agre1981 thanks for the detailed report! (I somehow totally missed this in my notifications).
Would you like to send a PR for this? Thanks a lot!

**Comment by fbiville** [comment] 2016-10-12 07:50
@agre1981 I cannot reproduce the issue you describe (see https://github.com/fbiville/liquigraph/pull/132, the build is passing and it should be failing). 
Are you sure the DB was not in a dirty state before running migrations again?

**Comment by fbiville** [comment] 2016-10-13 09:15
Hi, I will close this as it seems to me there is no issue.
@agre1981 feel free to re-open it if you think there is a bug.

**Comment by agre1981** [comment] 2016-10-14 08:37
Hello, 
1/ That is good practice commit or rollback transaction. we can not count that other will do it : )
2/ testcase should use LockableConnection.
GraphJdbcConnector
```
    public final Connection connect(Configuration configuration) {
        Connection connection = configuration.dataSourceConfiguration().get();
        return **LockableConnection.acquire(connection, lock);**
```
    }
3/ patch file for reproducing

**Comment by fbiville** [comment] 2016-10-14 08:44
Hi, thanks for the feedback.
I think you have enough material to submit a failing test, now, or? ;-)

**Comment by agre1981** [comment] 2016-10-14 08:46
```
    @Test
    public void does_not_leave_lock_when_invalid_statement_is_executed() throws Exception {

        assertThatThrownBy(new ThrowableAssert.ThrowingCallable() {
            @Override
            public void call() throws Throwable {
                Liquigraph liquigraph1 = new Liquigraph(
                		new GraphJdbcConnector() // for reproducing problem needed LocableConnection
                );
                
                liquigraph1.runMigrations(
                        new ConfigurationBuilder()
                                .withRunMode()
                                .withMasterChangelogLocation("changelog/changelog-invalid-statement.xml")
                                .withDataSource(new DataSource(){
									@Override
									public PrintWriter getLogWriter() throws SQLException {
										return null;
									}

									@Override
									public void setLogWriter(PrintWriter out) throws SQLException {
									}

									@Override
									public void setLoginTimeout(int seconds) throws SQLException {
									}

									@Override
									public int getLoginTimeout() throws SQLException {
										return 0;
									}

									@Override
									public Logger getParentLogger() throws SQLFeatureNotSupportedException {
										return null;
									}

									@Override
									public <T> T unwrap(Class<T> iface) throws SQLException {
										return null;
									}

									@Override
									public boolean isWrapperFor(Class<?> iface) throws SQLException {
										return false;
									}

									@Override
									public Connection getConnection() throws SQLException {
										return graphDatabase().connection();
									}

									@Override
									public Connection getConnection(String username, String password)
											throws SQLException {
										return graphDatabase().connection();
									}
                                	
                                })
                                //.withUri(graphDatabase().uri())
                                .build()
                );
            }
        })
                .isInstanceOf(RuntimeException.class)
                .hasCauseInstanceOf(SQLException.class);

        try (Connection connection = graphDatabase().connection();
             Statement statement = connection.createStatement();
             ResultSet resultSet = statement.executeQuery("MATCH (n:__LiquigraphLock) RETURN n")) {

            assertThat(resultSet.next()).isFalse();
        }
    }

```

**Comment by agre1981** [comment] 2016-10-14 08:46
Please reopen issue

**Comment by agre1981** [comment] 2016-10-14 08:51
This statement fails in LiquigraphLock
```
    private void releaseLock(Connection connection) {
        try (PreparedStatement statement = connection.prepareStatement(
                "MATCH (lock:__LiquigraphLock {uuid:{1}}) DELETE lock")) {

            statement.setString(1, uuid.toString());
            **statement.execute();
            connection.commit();**
        } catch (SQLException e) {
            LOGGER.error(
                    "Cannot remove __LiquigraphLock during cleanup.",
                    e
            );
        }
    }
```

**Comment by fbiville** [comment] 2016-10-14 09:25
What I meant by submitting a failing test is sending a PR, would you have time for this?

**Comment by agre1981** [comment] 2016-10-14 10:07
https://github.com/fbiville/liquigraph/pull/133

**Comment by agre1981** [comment] 2016-10-21 11:06
i fixed compilation errors. Now it should be fine. 
Alex

**Comment by fbiville** [comment] 2016-10-25 22:16
Ongoing investigation here: https://github.com/fbiville/liquigraph/pull/135.
I know how it fails, I don't understand yet how this happens. Thx for raising the issue, tho! We'll find out!

**Comment by fbiville** [comment] 2016-12-08 19:08
Please see https://github.com/fbiville/liquigraph/pull/135 last comment.
Let's discuss if you don't agree.

Closing for now.

**Closed by fbiville** 2016-12-08 19:08 UTC
Labels: bug
