### ISSUE TITLE
IndexOutOfBoundsException when username not provided

### ISSUE THREAD

**Issue by m007** [fbiville/liquigraph#130] opened 2016-10-06 15:05 UTC
With the following code
```java
        Configuration configuration = new ConfigurationBuilder()
                .withMasterChangelogLocation("changelog.xml")
                .withUri("jdbc:neo4j:http://localhost:7474")
                .withPassword(neo4jUserPassword)
                .withRunMode()
                .build();
        Liquigraph liquigraph = new Liquigraph();
        liquigraph.runMigrations(configuration);
```

and changelog

```xml
<?xml version="1.0" encoding="UTF-8"?>
<changelog xmlns="https://fbiville.github.io/liquigraph/schema/1.0/liquigraph.xsd">
    <changeset id="hello-world" author="you">
        <query>CREATE (n:Sentence {text:'Hello monde!'}) RETURN n</query>
    </changeset>
    <changeset id="hello-world-fixed" author="you">
        <query>MATCH (n:Sentence {text:'Hello monde!'}) SET n.text='Hello world!' RETURN n</query>
    </changeset>
</changelog>
```

I get an ArrayIndexOutOfBoundsException.
```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.neo4j.jdbc.http.HttpPreparedStatement.execute(HttpPreparedStatement.java:68)
	at org.liquigraph.core.io.lock.LiquigraphLock.releaseLock(LiquigraphLock.java:124)
	at org.liquigraph.core.io.lock.LiquigraphLock.release(LiquigraphLock.java:55)
	at org.liquigraph.core.io.lock.LockableConnection.close(LockableConnection.java:105)
	at org.liquigraph.core.io.lock.LockableConnection.acquire(LockableConnection.java:79)
	at org.liquigraph.core.io.GraphJdbcConnector.connect(GraphJdbcConnector.java:38)
	at org.liquigraph.core.api.MigrationRunner$ConnectionSupplier.get(MigrationRunner.java:125)
	at org.liquigraph.core.api.MigrationRunner$ConnectionSupplier.get(MigrationRunner.java:116)
	at org.liquigraph.core.api.MigrationRunner.runMigrations(MigrationRunner.java:70)
	at org.liquigraph.core.api.Liquigraph.runMigrations(Liquigraph.java:63)
        ... my code
```

Can anybody help with what is worng?

**Comment by fbiville** [comment] 2016-10-07 11:57
Did you figure it out? I see the issue is now closed.

**Comment by m007** [comment] 2016-10-07 15:41
Apparently one cannot use `.withPassword()` without giving `.withUsername()`, too. The default username in Neo4j is "neo4j" so I assumed that not giving `.withUsername()` would use "neo4j" as username. Eventually I solved it by providing the (default) username.

It would be interesting to see if you can reproduce this behaviour and maybe, either
+  provide a check for that (`IndexOutOfBoundsException` is not very telling for the user :wink: )
+ use "neo4j" as default if none is given

What do you think?

**Comment by fbiville** [comment] 2016-10-10 09:02
Yep, using a default username sounds like a good approach (and improving the error as well).
Would you like to try submitting a PR? :-)

**Comment by fpavageau** [comment] 2016-10-20 08:12
Since we're going to merge a PR, this issue should actually be open.

**Comment by fpavageau** [comment] 2016-10-20 08:20
And I botched the commit with a reference to the PR (#131) instead of the issue, so I'll close it manually...

**Closed by fpavageau** 2016-10-20 08:20 UTC
