### ISSUE TITLE
Liquigraph hangs with addition of changeset

### ISSUE THREAD

**Issue by airomega** [fbiville/liquigraph#82] opened 2016-06-01 16:10 UTC
We added a new file to our changeset. Since adding it it seems liquigraph hangs. There is no output from liquigraph that details what's going on. 

If we remove the file it works. If we only have one query in the - it works. We assumed it would be related to tabs or line endings however the file is in line with everything else. 

Can you offer any input on how to proceed? Is there a log file anywhere we can refer to?

**Comment by fbiville** [comment] 2016-06-01 18:56
Thanks for the report. That's interesting, I reproduce that with RC3 as well.

**Comment by fbiville** [comment] 2016-06-01 18:58
The weird thing is data is properly inserted, it seems to be a shutdown issue.

**Comment by airomega** [comment] 2016-06-01 19:04
Agreed. We've recreated the file and checked line breaks are consistent. The changesets run in but liquigraph doesn't shutdown as expected. Weirdly if there's one query in the final changeset it works - when you add a second query it hangs.

**Comment by fbiville** [comment] 2016-06-01 19:06
I'll debug against RC3 and keep you updated.

**Comment by fbiville** [comment] 2016-06-01 19:21
It seems the JDBC driver is hanging on the last query some unclear reasons for now:
```
java.lang.Thread.State: WAITING
	  at sun.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	  at org.apache.http.impl.conn.tsccm.WaitingThread.await(WaitingThread.java:158)
	  at org.apache.http.impl.conn.tsccm.ConnPoolByRoute.getEntryBlocking(ConnPoolByRoute.java:403)
	  at org.apache.http.impl.conn.tsccm.ConnPoolByRoute$1.getPoolEntry(ConnPoolByRoute.java:300)
	  at org.apache.http.impl.conn.tsccm.ThreadSafeClientConnManager$1.getConnection(ThreadSafeClientConnManager.java:224)
	  at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:391)
	  at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820)
	  at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
	  at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:732)
	  at org.restlet.ext.httpclient.internal.HttpMethodCall.sendRequest(HttpMethodCall.java:336)
	  at org.restlet.engine.adapter.ClientAdapter.commit(ClientAdapter.java:114)
	  at org.restlet.engine.adapter.HttpClientHelper.handle(HttpClientHelper.java:112)
	  at org.restlet.Client.handle(Client.java:180)
	  at org.restlet.routing.Filter.doHandle(Filter.java:159)
	  at org.restlet.routing.Filter.handle(Filter.java:206)
	  at org.restlet.resource.ClientResource.handle(ClientResource.java:1136)
	  at org.restlet.resource.ClientResource.handleOutbound(ClientResource.java:1225)
	  at org.restlet.resource.ClientResource.handle(ClientResource.java:1068)
	  at org.restlet.resource.ClientResource.handle(ClientResource.java:1044)
	  at org.restlet.resource.ClientResource.post(ClientResource.java:1453)
	  at org.neo4j.jdbc.internal.rest.TransactionalQueryExecutor.post(TransactionalQueryExecutor.java:98)
```

**Comment by fbiville** [comment] 2016-06-01 19:27
I guess somehow the connection pool is exhausted (thus blocking) because the JDBC driver does not close connections properly. Let me double check now.

**Comment by fbiville** [comment] 2016-06-01 20:29
I tried upgrading the legacy JDBC driver, the problem still occurs.

The main thread basically waits for a HTTP connection from the pool when it tries to insert the last changeset into the history graph.

There can be two explanations:

- one of JDBC driver/Restlet/Apache HttpClient is bugged
- Liquigraph connection management is wrong

I'll need more time to investigate the root cause.
@jexp did anyone mention such a behaviour before with the legacy JDBC driver?

**Comment by airomega** [comment] 2016-06-02 08:56
Hi,

My colleague @tanmayambre has found a solution to the problem and may point towards the issue. We removed the RETURN from all our queries and we no longer get the hang. Hopefully this helps the diagnosis.

**Comment by fbiville** [comment] 2016-08-27 19:55
Hi, we're in the process of using a fork of the original community JDBC driver for Neo4j 2.x.
I hope this will fix the issue you were suffering from.

I will close this issue for now. Feel free to reopen it if the problem occurs again.

**Closed by fbiville** 2016-08-27 19:55 UTC
Labels: bug
