### ISSUE TITLE
Error when running in larger changeset

### ISSUE THREAD

**Issue by airomega** [fbiville/liquigraph#76] opened 2016-05-02 11:47 UTC
I created a changeset with 17 create statements. When running liquigraph it would hang for a minute then throw the error below.

Splitting the 17 changesets into two seperate changesets fixed the error. 

```
12:32:53.167 [main] ERROR o.l.core.io.lock.LockableConnection - Cannot remove __LiquigraphLock during cleanup.
java.sql.SQLException: Error executing statement
	at org.neo4j.jdbc.internal.rest.TransactionalQueryExecutor.executeQuery(TransactionalQueryExecutor.java:224) ~[liquigraph-cli.jar:na]
	at org.neo4j.jdbc.internal.Neo4jConnection.executeQuery(Neo4jConnection.java:370) ~[liquigraph-cli.jar:na]
	at org.neo4j.jdbc.internal.Neo4jPreparedStatement.execute(Neo4jPreparedStatement.java:55) ~[liquigraph-cli.jar:na]
	at org.liquigraph.core.io.lock.LockableConnection.releaseLock(LockableConnection.java:310) [liquigraph-cli.jar:na]
	at org.liquigraph.core.io.lock.LockableConnection.close(LockableConnection.java:89) [liquigraph-cli.jar:na]
	at org.liquigraph.core.io.lock.LockableConnection.acquire(LockableConnection.java:71) [liquigraph-cli.jar:na]
	at org.liquigraph.core.io.GraphJdbcConnector.connect(GraphJdbcConnector.java:43) [liquigraph-cli.jar:na]
	at org.liquigraph.core.api.MigrationRunner.runMigrations(MigrationRunner.java:68) [liquigraph-cli.jar:na]
	at org.liquigraph.core.api.Liquigraph.runMigrations(Liquigraph.java:63) [liquigraph-cli.jar:na]
	at org.liquigraph.cli.LiquigraphCli.main(LiquigraphCli.java:119) [liquigraph-cli.jar:na]
Caused by: org.restlet.resource.ResourceException: Error executing statement
	at org.restlet.resource.ClientResource.doError(ClientResource.java:612) ~[liquigraph-cli.jar:na]
	at org.neo4j.jdbc.internal.rest.Resources$TransactionClientResource.doError(Resources.java:283) ~[liquigraph-cli.jar:na]
	at org.restlet.resource.ClientResource.handleInbound(ClientResource.java:1202) ~[liquigraph-cli.jar:na]
	at org.restlet.resource.ClientResource.handle(ClientResource.java:1069) ~[liquigraph-cli.jar:na]
	at org.restlet.resource.ClientResource.handle(ClientResource.java:1044) ~[liquigraph-cli.jar:na]
	at org.restlet.resource.ClientResource.post(ClientResource.java:1453) ~[liquigraph-cli.jar:na]
	at org.neo4j.jdbc.internal.rest.TransactionalQueryExecutor.post(TransactionalQueryExecutor.java:98) ~[liquigraph-cli.jar:na]
	at org.neo4j.jdbc.internal.rest.TransactionalQueryExecutor.begin(TransactionalQueryExecutor.java:76) ~[liquigraph-cli.jar:na]
	at org.neo4j.jdbc.internal.rest.TransactionalQueryExecutor.executeQuery(TransactionalQueryExecutor.java:214) ~[liquigraph-cli.jar:na]
	... 9 common frames omitted
Error executing statement (404) - {"results":[],"errors":[{"code":"Neo.ClientError.Transaction.UnknownId","message":"Unrecognized transaction id. Transaction may have timed out and been rolled back."}]}
	at org.restlet.resource.ClientResource.doError(ClientResource.java:612)
	at org.neo4j.jdbc.internal.rest.Resources$TransactionClientResource.doError(Resources.java:283)
	at org.restlet.resource.ClientResource.handleInbound(ClientResource.java:1202)
	at org.restlet.resource.ClientResource.handle(ClientResource.java:1069)
	at org.restlet.resource.ClientResource.handle(ClientResource.java:1044)
	at org.restlet.resource.ClientResource.handle(ClientResource.java:950)
	at org.restlet.resource.ClientResource.delete(ClientResource.java:570)
	at org.neo4j.jdbc.internal.rest.TransactionalQueryExecutor.rollback(TransactionalQueryExecutor.java:187)
	at org.neo4j.jdbc.internal.Neo4jConnection.close(Neo4jConnection.java:245)
	at org.liquigraph.core.io.lock.LockableConnection.close(LockableConnection.java:90)
	at org.liquigraph.core.io.lock.LockableConnection.acquire(LockableConnection.java:71)
	at org.liquigraph.core.io.GraphJdbcConnector.connect(GraphJdbcConnector.java:43)
	at org.liquigraph.core.api.MigrationRunner.runMigrations(MigrationRunner.java:68)
	at org.liquigraph.core.api.Liquigraph.runMigrations(Liquigraph.java:63)
	at org.liquigraph.cli.LiquigraphCli.main(LiquigraphCli.java:119)
Exception in thread "main" org.liquigraph.core.exception.LiquigraphLockException: Cannot create __LiquigraphLock lock
	Likely another Liquigraph execution is going on or has crashed.
	at org.liquigraph.core.io.lock.LockableConnection.tryWriteLock(LockableConnection.java:358)
	at org.liquigraph.core.io.lock.LockableConnection.acquireLock(LockableConnection.java:323)
	at org.liquigraph.core.io.lock.LockableConnection.acquire(LockableConnection.java:67)
	at org.liquigraph.core.io.GraphJdbcConnector.connect(GraphJdbcConnector.java:43)
	at org.liquigraph.core.api.MigrationRunner.runMigrations(MigrationRunner.java:68)
	at org.liquigraph.core.api.Liquigraph.runMigrations(Liquigraph.java:63)
	at org.liquigraph.cli.LiquigraphCli.main(LiquigraphCli.java:119)
Caused by: java.sql.SQLException: Error executing query CREATE (:__LiquigraphLock {name:'John', uuid:{1}})
 with params {1=4689adcb-4f39-493a-a82a-faa7f8bf24be}
	at org.neo4j.jdbc.internal.Neo4jConnection.executeQuery(Neo4jConnection.java:379)
	at org.neo4j.jdbc.internal.Neo4jPreparedStatement.execute(Neo4jPreparedStatement.java:55)
	at org.liquigraph.core.io.lock.LockableConnection.tryWriteLock(LockableConnection.java:354)
	... 6 more
Caused by: java.lang.RuntimeException: Error executing cypher statement(s) [{code=Neo.ClientError.Schema.ConstraintViolation, message=Node 6 already exists with label __LiquigraphLock and property "name"=[John]}]
	at org.neo4j.jdbc.internal.rest.StreamingParser.handleErrors(StreamingParser.java:341)
	at org.neo4j.jdbc.internal.rest.StreamingParser.skipTo(StreamingParser.java:315)
	at org.neo4j.jdbc.internal.rest.StreamingParser.nextResult(StreamingParser.java:130)
	at org.neo4j.jdbc.internal.rest.StreamingParser$2.hasNext(StreamingParser.java:265)
	at org.neo4j.jdbc.internal.rest.TransactionalQueryExecutor.executeQuery(TransactionalQueryExecutor.java:215)
	at org.neo4j.jdbc.internal.Neo4jConnection.executeQuery(Neo4jConnection.java:370)
	... 8 more
```

**Comment by fbiville** [comment] 2016-05-02 12:50
Would you mind sharing the queries (or similar) you were trying to run? It looks like you are trying to fit too much work in a single transaction (thus exceeding the default timeout).

**Comment by airomega** [comment] 2016-05-02 12:59
I've sent via email.

**Comment by fbiville** [comment] 2016-05-02 13:04
OK, I need to dig in the JDBC driver sources. We reuse the same statement to execute queries within a transaction but I'm not sure how this translates into HTTP calls to the remote instance.

**Comment by fbiville** [comment] 2016-05-09 11:51
Would you mind posting a `PROFILE` result for each of the offending queries?
In case they are indeed resource intensive, then ongoing work defined in issue #77 will solve your problem, I think.

**Comment by fbiville** [comment] 2016-05-10 22:19
OK, now that I've read carefully the stack trace.
It seems that your graph instance is in a dirty state, because the Liquigraph lock node was still there. 

@airomega are you sure you started from a clean instance? You did not interrupt the previous execution?

**Comment by airomega** [comment] 2016-05-16 10:26
Hey, 

Sorry, was away for my PC for a few days. 

I didn't think I was in a dirty state. I hit the lock state quite a lot and simply delete all nodes and try again. As I stated  above, the behaviour was the application hung for a a long time before erroring. I think the lock state/stack trace are produced due to liquigraph running than the lock existing prior. Is the lock state recreated during a changeset or is it instantiated at the start and persists until the changeset completes.  

I'll double check by rerunning against a verified blank db instance

**Comment by fbiville** [comment] 2016-05-16 11:25
The lock node is set at the first connection and is remove upon Liquigraph shutdown.
The implementation is done with a JDBC Connection decorator: https://github.com/fbiville/liquigraph/blob/master/liquigraph-core/src/main/java/org/liquigraph/core/io/lock/LockableConnection.java#L64.

**Comment by fbiville** [comment] 2016-05-18 19:27
Hello, @airomega can you reproduce the issue or did it happen only once?

**Comment by airomega** [comment] 2016-05-19 12:14
Hi,

Apologies, I've been on holiday the last few weeks hence my continual slow replies.

I wasn't able to reproduce so the mistake was likely mine. If it happens again I'll let you know

**Comment by fbiville** [comment] 2016-05-19 13:09
Ok, I'll close the issue for now.

**Closed by fbiville** 2016-05-19 13:09 UTC
Labels: bug
